name: fedora-frieser
description: Fedora Frieser

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 41 

modules:
  - type: files
    files:
      - source: system
        destination: / 

  - type: rpm-ostree
    repos:
    install:
      - kitty
#      - sshuttle
#      - docker
      - zsh
#      - vim
      - gnome-pomodoro
      - gnome-boxes
    remove:
      - firefox
      - firefox-langpacks 

  - type: default-flatpaks
    notify: true 
    system:
      install:
        - com.jetbrains.GoLand
        - com.rtosta.zapzap
        - com.spotify.Client
        - com.ticktick.TickTick
        - md.obsidian.Obsidian
        - org.gnome.Firmware
        - org.mozilla.firefox
        - org.videolan.VLC
        - org.gnome.Extensions
        - com.valvesoftware.Steam
        - org.gnome.TextEditor
        - org.gnome.Cheese
        - com.usebottles.bottles
        - com.github.tchx84.Flatseal
        - io.github.flattool.Warehouse
      remove:
      
  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode # don't add spaces or "Nerd Font" suffix.
        - Hack
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Roboto
        - Open Sans    
  - type: gnome-extensions
    install:
      - Focus
      - Just Perfection
      - Mouse Follows Focus
      - Caffeine
  - type: chezmoi
    repository: https://github.com/frieser/dotfiles 
    branch: main
  - type: signing 

